config/routes.rb
Rails.application.routes.draw do
  root to: 'twits#index'
resources :twits do
  collection do
    post :confirm
  end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/twit.rb
class Twit < ApplicationRecord
  validates :content, presence:true
  validates :content, length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/twits_controller.rb
class TwitsController < ApplicationController
      before_action :set_twit, only: [:show, :edit, :update, :destroy]

    def index
      @twit = Twit.all
    end

    def new
      @twit = Twit.new
    end

    def show
      @twit.destroy
      redirect_to twits_path, notice: "Le Tweet est supprimé !"
    end

    def edit
    end

    def create
      @twit = Twit.new(twit_params)
      if params[:back]
        render :new
      else
        if @twit.save
          redirect_to twits_path, notice: "Le Tweet est créé !"
        else
          render :new
        end
      end
    end

    def update
      if @twit.update(twit_params)
        redirect_to twits_path, notice: "Le Tweet est modifié !"
      else
        render :edit
      end
    end

    def confirm
      @twit = Twit.new(twit_params)
      render :new if @twit.invalid?
    end

    private

    def twit_params
      params.require(:twit).permit(:title, :content)
    end

    def set_twit
      @twit = Twit.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twits_helper.rb
module TwitsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_twits_path
    elsif action_name == 'edit'
      twit_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweeeterapp</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header clearfix">
      <div class="menu_1">
        <%= link_to twits_path do %>
          <%= image_tag "logo.png", size: '100x100', class: 'twit-bird' %>
        <% end %>
          <p class="home-1"> ○ Accueil</p>
          <p> ○ Information</p>
          <p> ○ Notification</p>
          <p> ○ Message</p>
       <div class="menu_1_btn">
         <%= link_to 'Tweetté', new_twit_path, class: "menu-btn" %>
       </div>
      </div>
    </header>
    <article class="twits">
      <%= yield %>
    </article>
    <aside class="menu_2">
      <div class="search-box">
        <%= image_tag "search.png", size: '14x14', class: 'search-img' %>
      </div>
      <div class="news">
        <h2>A lire !</h2>
        <p>News 1</p>
        <p>News 2</p>
        <p>News 3</p>
        <p>News 4</p>
        <p>News 5</p>
        <p>News 6</p>
        <p>News 7</p>
        <p>News 8</p>
        <p class="more_recommend">See More</p>
      </div>
      <div class="users">
        <h2>Users</h2>
        <div>
          <table>
            <tr>
              <td><%= image_tag "logBenjust.jpg", size: '50x50', class: "account_pic" %></td>
              <td><span class="bold_span">C'est le BÉNIN</span><br>
                  <span class="grey_span">@JUSTICE</span>
              </td>
            </tr>
          </table>
        </div>
        <div>
          <table>
            <tr>
              <td><%= image_tag "drapo.png", size: '50x50', class: "account_pic" %></td>
              <td><span class="bold_span">Utilisateur 1</span><br>
                  <span class="grey_span">@divedive1</span></td>
            </tr>
          </table>
        </div>
        <div>
          <table>
            <tr>
              <td><%= image_tag "benlogo.png", size: '50x50', class: "account_pic" %></td>
              <td><span class="bold_span">Utilisateur 2</span><br>
                  <span class="grey_span">@divedive2</span>
              </td>
            </tr>
          </table>
        </div>
        <div>
          <table>
            <tr>
              <td><%= image_tag "logBenjust.jpg", size: '50x50', class: "account_pic" %></td>
              <td><span class="bold_span">Utilisateur 3</span><br>
                  <span class="grey_span">@divedive3</span>
              </td>
            </tr>
          </table>
        </div>
        <p class="more_recommend">Voir plus</p>
      </div>
      <footer class="footer">
        <div class="footer_info">
          <p>Terms Of Use</p>
          <p>Privacy Policy</p>
          <p>Cookies</p>
          <p>Ads</p>
          <p>More</p>
          <p>© Mars 2022#Tweeeterapp, Inc.</p>
        </div>
      </footer>
    </aside>
  </body>
</html>

app/views/twits/_form.html.erb
<%= form_with(model: @twit, local: true ,url: choose_new_or_edit) do |form| %>
  <% if @twit.errors.any? %>
    <div id="error_explanation">
      <h2>Il y a <%= @twit.errors.count %> erreur </h2>
      <ul>
      <% @twit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="twit_content">
    <%= form.text_field :content, class: 'input', id: 'input-text' %>
  </div>
  <br>
  <%= form.submit "Tweetté" %>
<% end %>

<%= link_to "Retour", twits_path %>

app/views/twits/confirm.html.erb
<div class="home_0">
  <div class="twit_btn_mini"><br>
  <%= image_tag "benlogo.png", size: '48x48' %>
  </div>
</div>
<div class="box_0">
  <%= image_tag "logo2.png", size: '90x50', class: "acc_pic" %>
  <h3 style="padding-left: 200px;">TWITTER_CLONE</h3>
</div>

<h1>Écran de confirmation</h1>
<h3>Voulez-vous vraiment poster un tweet !</h3>

<%= form_with(model: @twit, url: twits_path, local: true) do |form| %>
  <%= form.hidden_field :content %>

    <p><%= @twit_content %></p>
  <%= form.submit "Tweetté" %>

  <%= form.submit "Retourner", name: 'back' %>
<% end %>

app/views/twits/edit.html.erb
<%= render 'form' %>

app/views/twits/index.html.erb
<span id="notice"><%= notice %></span>

<div class="home_0">
  <div class="twit_btn_mini"><br>
  <%= image_tag "benlogo.png", size: '48x48' %>
  </div>
</div>
<div class="box_0">
  <%= image_tag "logo2.png", size: '90x50', class: "acc_pic" %>
  <h3 style="padding-left: 200px;">TWITTER_CLONE</h3>
</div>
<div class="box_btn_0">
  <div class="twit_btn_mini">
    <%= link_to 'Tweetté', new_twit_path, class: "menu_btn_mini" %>
  </div>
</div>
<div class="bold_border"></div>
    <% @twit.each do |twit| %>
    <div class="twit_box">
      <table>
        <tr>
          <td class="img">
            <%= image_tag "logo2.png", size: '50x50', class: "acc_pic" %>
          </td>
          <td class="name_and_content">
        <span class="acc_name">Le BÉNIN</span>
        <span class="acc_name_thin">JUSTICE</span>
    <div class="main_twit"><%= twit.content %></div>
          </td>
          <td class="edit">
            <%= link_to edit_twit_path(twit.id)do %>
            <%= image_tag "edit.png", size: '14x14' %>
            <% end %>
          </td>
          <td class="edit">
            <%= link_to twit_path(twit.id)do %>
            <%= image_tag "delete.png", size: '14x14' %>
            <% end %>
          </td>
          </tr>
          <tr>
            <td></td>
            <td>
    <div class="twit_box_gadget">
            <%= image_tag "rep.png", size: '14x14', class: 'gadget-pics' %>
            <%= image_tag "retwit.png", size: '14x14', class: 'gadget-pics' %>
            <%= image_tag "fav.png", size: '14x14', class: 'gadget-pics' %>
            <%= image_tag "link.png", size: '14x14', class: 'gadget-pics' %>
    </div>
        </td>
        <td></td>
        <td></td>
    </tr>
  </table>
</div>
<% end %>

app/views/twits/new.html.erb
<div class="home_0">
  <div class="twit_btn_mini"><br>
  <%= image_tag "benlogo.png", size: '48x48' %>
  </div>
</div>
<div class="box_0">
  <%= image_tag "logo2.png", size: '90x50', class: "acc_pic" %>
  <h3 style="padding-left: 200px;">TWITTER_CLONE</h3>
</div>

<%= render 'form' %>

app/views/twits/show.html.erb
<h1>Ètes_vous sûre ?</h1>
<p>Contents : <%= @twit.content %></p><br>

<%= link_to 'Destroy', twit_path(@twit.id), method: :delete, class: "button" %>
<%= link_to 'Twit Screen', twits_path %>